/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-03-20 00:45:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Contact Us - NexoraSkill</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"${pageContext.request.contextPath}/css/contactus.css\">\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"${pageContext.request.contextPath}/images/favicon.ico\">\r\n");
      out.write("  <style>\r\n");
      out.write("    /* General Reset */\r\n");
      out.write("    * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    :root {\r\n");
      out.write("      --primary-color: #009acd;\r\n");
      out.write("      --secondary-color: #00ffcc;\r\n");
      out.write("      --accent-color: #ff6b6b;\r\n");
      out.write("      --dark-color: #0a192f;\r\n");
      out.write("      --text-color: #ffffff;\r\n");
      out.write("      --hover-color: #007ba7;\r\n");
      out.write("      --glow-color: rgba(0, 255, 204, 0.6);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("      background: var(--dark-color);\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Header Section */\r\n");
      out.write("    .header {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      z-index: 1000;\r\n");
      out.write("      background-color: var(--dark-color);\r\n");
      out.write("      padding: 20px 0;\r\n");
      out.write("      border-bottom: 1px solid #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("      width: 90%;\r\n");
      out.write("      max-width: 1200px;\r\n");
      out.write("      margin: 0 auto;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 10px;\r\n");
      out.write("      font-size: 1.5rem;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo img {\r\n");
      out.write("      height: 40px;\r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo:hover img {\r\n");
      out.write("      transform: rotate(15deg);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar ul {\r\n");
      out.write("      list-style: none;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar ul li a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      transition: color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar ul li a:hover,\r\n");
      out.write("    .navbar ul li a.active {\r\n");
      out.write("      color: var(--primary-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-buttons {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-login, .btn-signup {\r\n");
      out.write("      padding: 10px 20px;\r\n");
      out.write("      border-radius: 25px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-login {\r\n");
      out.write("      background: transparent;\r\n");
      out.write("      border: 2px solid var(--primary-color);\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-login:hover {\r\n");
      out.write("      background: var(--primary-color);\r\n");
      out.write("      color: var(--dark-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-signup {\r\n");
      out.write("      background: var(--primary-color);\r\n");
      out.write("      color: var(--dark-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-signup:hover {\r\n");
      out.write("      background: var(--hover-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Hero Section */\r\n");
      out.write("    .hero {\r\n");
      out.write("      padding: 150px 0 100px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      background-color: var(--dark-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero h1 {\r\n");
      out.write("      font-size: 3rem;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      text-shadow: 0 0 10px var(--glow-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero p {\r\n");
      out.write("      font-size: 1.2rem;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Contact Information Section */\r\n");
      out.write("    .contact-info {\r\n");
      out.write("      padding: 80px 0;\r\n");
      out.write("      background-color: var(--dark-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .contact-info h2 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-bottom: 40px;\r\n");
      out.write("      font-size: 2.5rem;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      text-shadow: 0 0 10px var(--glow-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-grid {\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-item {\r\n");
      out.write("      background-color: #1f1f1f;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-item:hover {\r\n");
      out.write("      transform: translateY(-10px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-item i {\r\n");
      out.write("      font-size: 32px;\r\n");
      out.write("      margin-bottom: 15px;\r\n");
      out.write("      color: var(--primary-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-item h3 {\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-item p {\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .map {\r\n");
      out.write("      margin-top: 40px;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Contact Form Section */\r\n");
      out.write("    .contact-form {\r\n");
      out.write("      padding: 80px 0;\r\n");
      out.write("      background-color: var(--dark-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .contact-form h2 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-bottom: 40px;\r\n");
      out.write("      font-size: 2.5rem;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      text-shadow: 0 0 10px var(--glow-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .contact-form form {\r\n");
      out.write("      max-width: 600px;\r\n");
      out.write("      margin: 0 auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input,\r\n");
      out.write("    .form-group textarea {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border: 1px solid #333;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      background-color: #1f1f1f;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group textarea {\r\n");
      out.write("      resize: vertical;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .contact-form .btn-primary {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      font-size: 18px;\r\n");
      out.write("      background: var(--primary-color);\r\n");
      out.write("      color: var(--dark-color);\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .contact-form .btn-primary:hover {\r\n");
      out.write("      background: var(--hover-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Footer Section */\r\n");
      out.write("    .footer {\r\n");
      out.write("      background-color: var(--dark-color);\r\n");
      out.write("      padding: 40px 0;\r\n");
      out.write("      border-top: 1px solid #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer .container {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      flex-wrap: wrap;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-links {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-links a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      transition: color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-links a:hover {\r\n");
      out.write("      color: var(--primary-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-social {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-social a {\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("      transition: color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-social a:hover {\r\n");
      out.write("      color: var(--primary-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-newsletter {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-newsletter p {\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-newsletter form {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-newsletter input {\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border: 1px solid #333;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      background-color: #1f1f1f;\r\n");
      out.write("      color: var(--text-color);\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-newsletter button {\r\n");
      out.write("      padding: 10px 20px;\r\n");
      out.write("      background: var(--primary-color);\r\n");
      out.write("      color: var(--dark-color);\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-newsletter button:hover {\r\n");
      out.write("      background: var(--hover-color);\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header Section -->\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("      <img src=\"./images/favicon-32x32.png\" alt=\"NexoraSkill Logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation Menu -->\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("        <li><a href=\"courses.jsp\">Courses</a></li>\r\n");
      out.write("        <li><a href=\"registration.jsp\">Registration</a></li>\r\n");
      out.write("        <li><a href=\"aboutus.jsp\">About Us</a></li>\r\n");
      out.write("        <li><a href=\"contact us.jsp\" class=\"active\">Contact Us</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Call-to-Action Buttons -->\r\n");
      out.write("    <div class=\"auth-buttons\">\r\n");
      out.write("      <a href=\"logIn.jsp\" class=\"btn-login\">Login</a>\r\n");
      out.write("      <a href=\"signUp.jsp\" class=\"btn-signup\">Sign Up</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<section class=\"hero\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h1>We’re Here to Help!</h1>\r\n");
      out.write("    <p>Reach out to us for assistance with course registration, technical issues, or general inquiries.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Contact Information Section -->\r\n");
      out.write("<section class=\"contact-info\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h2>Get in Touch</h2>\r\n");
      out.write("    <div class=\"info-grid\">\r\n");
      out.write("      <div class=\"info-item\">\r\n");
      out.write("        <i class=\"fas fa-phone\"></i>\r\n");
      out.write("        <h3>Phone</h3>\r\n");
      out.write("        <p>+1 (123) 456-7890</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"info-item\">\r\n");
      out.write("        <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("        <h3>Email</h3>\r\n");
      out.write("        <p>support@nexoraskill.com</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"info-item\">\r\n");
      out.write("        <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("        <h3>Address</h3>\r\n");
      out.write("        <p>123 Education Lane, Campus City, CC 12345</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"map\">\r\n");
      out.write("      <iframe src=\"https://www.google.com/maps/embed?pb=...\" width=\"100%\" height=\"400\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\"></iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Contact Form Section -->\r\n");
      out.write("<section class=\"contact-form\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h2>Send Us a Message</h2>\r\n");
      out.write("    <form action=\"${pageContext.request.contextPath}/contact\" method=\"POST\">\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" name=\"name\" placeholder=\"Your Name\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"email\" name=\"email\" placeholder=\"Your Email\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <input type=\"text\" name=\"subject\" placeholder=\"Subject\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <textarea name=\"message\" placeholder=\"Your Message\" rows=\"5\" required></textarea>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\">Send Message</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
