/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2025-03-23 12:28:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>NexoraSkill - Student Course Registration System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"./images/favicon.ico\">\r\n");
      out.write("    <!-- Add Google Fonts for Poppins -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General   Reset*/\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #009acd;\r\n");
      out.write("            --secondary-color: #00ffcc;\r\n");
      out.write("            --accent-color: #ff6b6b;\r\n");
      out.write("            --dark-color: #0a192f;\r\n");
      out.write("            --text-color: #ffffff;\r\n");
      out.write("            --hover-color: #007ba7;\r\n");
      out.write("            --glow-color: rgba(0, 255, 204, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: var(--dark-color);\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Header Section */\r\n");
      out.write("        .header {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            background: var(--dark-color);\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo img {\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo:hover img {\r\n");
      out.write("            transform: rotate(15deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar ul li a {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar ul li a:hover {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .auth-buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login, .btn-signup {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login {\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: 2px solid var(--primary-color);\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login:hover {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            color: var(--dark-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-signup {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            color: var(--dark-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-signup:hover {\r\n");
      out.write("            background: var(--hover-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hero Section */\r\n");
      out.write("        .hero {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            padding: 0 5%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-content {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            animation: slideInLeft 1s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-title {\r\n");
      out.write("            font-size: 3.5rem;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("            text-shadow: 0 0 10px var(--glow-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-subtext {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-cta {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta-button {\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .primary-cta {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            color: var(--dark-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .primary-cta:hover {\r\n");
      out.write("            background: var(--hover-color);\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 5px 20px var(--glow-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .secondary-cta {\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border: 2px solid var(--primary-color);\r\n");
      out.write("            color: var(--text-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .secondary-cta:hover {\r\n");
      out.write("            background: var(--primary-color);\r\n");
      out.write("            color: var(--dark-color);\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-visual {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 500px;\r\n");
      out.write("            animation: slideInRight 1s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .glowing-circle {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: radial-gradient(circle, var(--glow-color), transparent 70%);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            animation: glow 3s infinite alternate;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .animated-grid {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: repeating-linear-gradient(\r\n");
      out.write("                    45deg,\r\n");
      out.write("                    transparent,\r\n");
      out.write("                    transparent 25%,\r\n");
      out.write("                    var(--glow-color) 25%,\r\n");
      out.write("                    var(--glow-color) 50%\r\n");
      out.write("            );\r\n");
      out.write("            background-size: 20px 20px;\r\n");
      out.write("            animation: moveGrid 5s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideInLeft {\r\n");
      out.write("            from {\r\n");
      out.write("                transform: translateX(-100px);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                transform: translateX(0);\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideInRight {\r\n");
      out.write("            from {\r\n");
      out.write("                transform: translateX(100px);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                transform: translateX(0);\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes glow {\r\n");
      out.write("            0% {\r\n");
      out.write("                opacity: 0.6;\r\n");
      out.write("            }\r\n");
      out.write("            100% {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes moveGrid {\r\n");
      out.write("            0% {\r\n");
      out.write("                background-position: 0 0;\r\n");
      out.write("            }\r\n");
      out.write("            100% {\r\n");
      out.write("                background-position: 40px 40px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .hero {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .hero-visual {\r\n");
      out.write("                width: 300px;\r\n");
      out.write("                height: 300px;\r\n");
      out.write("                margin-top: 30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .hero-title {\r\n");
      out.write("                font-size: 2.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .hero-subtext {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Header Section -->\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <link rel=\"icon\" type=\"image/png\" href=\"./images/favicon-32x32.png\">\r\n");
      out.write("            <span>NexoraSkill</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"./images/favicon-32x32.png\" alt=\"NexoraSkill Logo\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#home\">Home</a></li>\r\n");
      out.write("                <li><a href=\"courses.jsp\">Courses</a></li>\r\n");
      out.write("                <li><a href=\"registration.jsp\">Registration</a></li>\r\n");
      out.write("                <li><a href=\"aboutus.jsp\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"auth-buttons\">\r\n");
      out.write("            <a href=\"logIn.jsp\" class=\"btn-login\">Login</a>\r\n");
      out.write("            <a href=\"signUp.jsp\" class=\"btn-signup\">Sign Up</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<section class=\"hero\">\r\n");
      out.write("    <div class=\"hero-content\">\r\n");
      out.write("        <h1 class=\"hero-title\">Welcome to NexoraSkill</h1>\r\n");
      out.write("        <p class=\"hero-subtext\">Your gateway to mastering new skills and achieving your goals.</p>\r\n");
      out.write("        <div class=\"hero-cta\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/courses.jsp\" class=\"cta-button primary-cta\">Explore Courses</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/registration.jsp\" class=\"cta-button secondary-cta\">Register Now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hero-visual\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"./images/favicon-32x32.png\">\r\n");
      out.write("        <div class=\"glowing-circle\"></div>\r\n");
      out.write("        <div class=\"animated-grid\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Ensure FontAwesome is included -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/YOUR-KIT-ID.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
